query MyQuery($bookId: Int!) {
  books_by_pk(id: $bookId) {
    author
    available
    bookImage
    created_at
    genre
    id
    title
    rent_book {
      bookId
      id
      rent_day
      return_date
      userId
      user_rent {
        username
        phone
        email
      }
      payments {
        amount
        payment_method
        status
        tx_ref
        updated_at
        user_id
        id
        currency
        created_at
        rent_id
      }
    }
  }
}
